####
#
# The following example shows how a model can be quantized with
# mixed precision entirely with primitives within `compressed-tensors`.
#
# Attention layers are quantized to FP8 (weights + static activations)
# and MLP layers are quantized to NVFP4 (weights + locally dynamic activations).
#
# The config is defined in `./mixed_precision_config.json`, which uses
# regex-based targets to route different layer types to different schemes.
#
####

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import math
from pathlib import Path

import torch
from compressed_tensors.compressors import ModelCompressor
from compressed_tensors.offload import update_offload_parameter
from compressed_tensors.quantization import (
    QuantizationConfig,
    QuantizationStatus,
    QuantizationStrategy,
    apply_quantization_config,
)
from compressed_tensors.quantization.utils import calculate_qparams, generate_gparam
from datasets import load_dataset
from torch.utils.data import DataLoader, RandomSampler
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, DefaultDataCollator


config_file = Path(__file__).parent / "mixed_precision_config.json"
MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
DATASET_ID = "HuggingFaceH4/ultrachat_200k"
DATASET_SPLIT = "train_sft"
NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 2048
output_dir = "./Meta-Llama-3-8B-Instruct-FP8-NVFP4"
device = "cuda:0" if torch.cuda.is_available() else "cpu"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map=device, torch_dtype="auto"
)
model.eval()
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

config = QuantizationConfig.model_validate_json(config_file.read_text())
config.quantization_status = QuantizationStatus.CALIBRATION

apply_quantization_config(model, config)


def update_scales_hook(
    module: torch.nn.Module, input: torch.Tensor, _output: torch.Tensor
):
    quantization_scheme = getattr(module, "quantization_scheme", None)
    if not quantization_scheme:
        return

    # -- weight scales --
    # The weight calibration differs between the two schemes:
    #
    # FP8 (attention layers): uses TENSOR strategy, so we compute a single
    #   per-tensor min/max via torch.aminmax and derive one scale for the
    #   entire weight matrix.
    #
    # NVFP4 (MLP layers): uses TENSOR_GROUP strategy with group_size=16,
    #   so we reshape the weight into groups, compute per-group min/max,
    #   and derive a scale per group. NVFP4 also requires a global_scale
    #   (generated by generate_gparam) that maps the per-group FP8 scales
    #   into the full FP8 dynamic range. The global_scale is passed into
    #   calculate_qparams to produce FP8-dtype group scales.
    quantization_args = getattr(quantization_scheme, "weights", None)
    if quantization_args is not None:
        weight = module.weight.data
        group_size = quantization_args.group_size
        strategy = quantization_args.strategy

        # For group/tensor_group strategies, reshape and compute per-group min/max
        if (
            strategy
            in (QuantizationStrategy.GROUP, QuantizationStrategy.TENSOR_GROUP)
            and group_size is not None
            and group_size > 0
        ):
            reshaped = weight.unflatten(
                -1, (math.ceil(weight.shape[-1] / group_size), group_size)
            )
            min_val = reshaped.amin(dim=-1)
            max_val = reshaped.amax(dim=-1)
        else:
            # For tensor strategy (FP8), a single min/max across all elements
            min_val, max_val = torch.aminmax(weight)

        if strategy == QuantizationStrategy.TENSOR_GROUP:
            # NVFP4: compute global_scale = (fp8_max * fp4_max) / max(abs(weight))
            # This ensures per-group scales fit within the FP8 range
            global_scale = generate_gparam(min_val, max_val)
            update_offload_parameter(module, "weight_global_scale", global_scale)
            scale, _ = calculate_qparams(
                min_val, max_val, quantization_args, global_scale=global_scale
            )
        else:
            # FP8: straightforward scale from tensor-level min/max
            scale, _ = calculate_qparams(min_val, max_val, quantization_args)

        update_offload_parameter(module, "weight_scale", scale)

    # -- input activations --
    # Only calibrated for static schemes (FP8 attention layers).
    # NVFP4 MLP layers use locally dynamic activations (dynamic="local"),
    # meaning input scales are computed at runtime, not during calibration.
    quantization_args = getattr(quantization_scheme, "input_activations", None)
    if quantization_args is not None and not quantization_args.dynamic:
        min_val, max_val = torch.aminmax(input[0])
        scale, _ = calculate_qparams(min_val, max_val, quantization_args)
        update_offload_parameter(module, "input_scale", scale)


model.apply(lambda module: module.register_forward_hook(update_scales_hook))

# Load and preprocess calibration dataset
ds = load_dataset(DATASET_ID, split=f"{DATASET_SPLIT}[:{NUM_CALIBRATION_SAMPLES}]")
ds = ds.shuffle(seed=42)


def preprocess(example):
    return {
        "text": tokenizer.apply_chat_template(
            example["messages"],
            tokenize=False,
        )
    }


ds = ds.map(preprocess)


def tokenize(sample):
    return tokenizer(
        sample["text"],
        padding=False,
        max_length=MAX_SEQUENCE_LENGTH,
        truncation=True,
        add_special_tokens=False,
    )


tokenized_dataset = ds.map(tokenize, remove_columns=ds.column_names)
data_loader = DataLoader(
    tokenized_dataset,
    batch_size=1,
    collate_fn=DefaultDataCollator(),
    sampler=RandomSampler(tokenized_dataset),
)

with torch.no_grad():
    for idx, sample in tqdm(enumerate(data_loader), desc="Running calibration"):
        sample = {k: v.to(model.device) for k, v in sample.items()}
        _ = model(**sample)

        if idx >= NUM_CALIBRATION_SAMPLES:
            break

# apply compression
compressor = ModelCompressor.from_pretrained_model(model)
compressor.compress_model(model)

# save quantized model
model.save_pretrained(output_dir)
compressor.update_config(output_dir)
